version: '2.1'

jobs:
  build:
    docker:
      - image: maven:3.8.8-openjdk-17
    steps:
      - checkout
      - run:
          name: Set up Maven cache
          command: |
            mkdir -p ~/.m2
      - restore_cache:
          keys:
            - maven-deps-{{ checksum "pom.xml" }}
      - run:
          name: Build with Maven
          command: mvn clean package
      - save_cache:
          paths:
            - ~/.m2/repository
          key: maven-deps-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target
          destination: build-artifacts

  test:
    docker:
      - image: maven:3.8.8-openjdk-17
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-deps-{{ checksum "pom.xml" }}
      - run:
          name: Run tests
          command: mvn test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target
          destination: test-artifacts

  deploy:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Deploy to production
          command: |
            echo "Deploying application..."
            # Add deployment commands (like moving files, git push, etc.)

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test